[deploy]
bucket = 'cfn-artifactscruddur'
region = 'us-east-1'
stack_name = 'CrdFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:319506457158:certificate/5a4320fa-bdba-486b-b021-8f9e4ab89b25'

WwwBucketName = 'www.rietta.online'
RootBucketName = 'rietta.online'

HostedZoneId = 'Z050140339WWV52RV7AGX'
